import React, { useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import { ArrowLeft, ArrowUpRight, Check, Code2, LoaderCircle, Send, Sparkles } from "lucide-react";

export default function DeveloperConnect() {
  const [form,setForm]=useState({name:"",email:"",projectType:"Full stack website",budget:"Flexible",message:""}); const [state,setState]=useState("idle"); const [error,setError]=useState("");
  const change=e=>setForm({...form,[e.target.name]:e.target.value});
  const submit=async e=>{e.preventDefault();setState("loading");setError("");try{await axios.post("/api/v1/builder/connect",form);setState("sent");}catch(err){setError(err.response?.data?.message||"Could not send your request. Please try again.");setState("idle");}};
  return <main className="wc-page"><header className="wc-top"><Link to="/builder"><ArrowLeft size={16}/> Back to studio</Link><span>CODEBRICKET <b>STUDIO</b></span></header><div className="wc-layout"><section className="wc-intro"><div className="wc-orbit wc-orbit-one"/><div className="wc-orbit wc-orbit-two"/><span className="wc-eyebrow"><Sparkles size={14}/> BUILD SOMETHING BIGGER</span><h1>Your idea.<br/>Our <em>developers.</em></h1><p>Tell us what you’re imagining. Our team will help turn your idea into a polished, working website.</p><div className="wc-benefit"><span><Code2 size={17}/></span><div><b>Full stack, end to end</b><small>Design, development and launch support</small></div></div><div className="wc-benefit"><span><ArrowUpRight size={17}/></span><div><b>Built around your business</b><small>A site that works the way you do</small></div></div><div className="wc-intro-caption">GOOD IDEAS DESERVE GOOD EXECUTION &nbsp; ✳</div></section><section className="wc-form-wrap">{state==="sent"?<div className="wc-success"><div><Check size={28}/></div><span className="wc-eyebrow">REQUEST RECEIVED</span><h2>Thanks for reaching out.</h2><p>Your project details are with our team. We’ll get back to you at the email you provided.</p><Link to="/builder">Return to your studio <ArrowUpRight size={16}/></Link></div>:<form className="wc-form" onSubmit={submit}><span className="wc-eyebrow">LET’S TALK</span><h2>Tell us about your project.</h2><p>Share a few details and we’ll be in touch.</p>{error&&<div className="wc-error" role="alert">{error}</div>}<div className="wc-input-grid"><label>Your name<input name="name" value={form.name} onChange={change} placeholder="e.g. Aanya Sharma" required maxLength="100"/></label><label>Email address<input name="email" type="email" value={form.email} onChange={change} placeholder="you@yourbrand.com" required/></label></div><div className="wc-input-grid"><label>What are you building?<select name="projectType" value={form.projectType} onChange={change}><option>Full stack website</option><option>Online store</option><option>Business website</option><option>Web application</option><option>Something else</option></select></label><label>Approximate budget<select name="budget" value={form.budget} onChange={change}><option>Flexible</option><option>Under ₹50,000</option><option>₹50,000 – ₹1,50,000</option><option>₹1,50,000 – ₹5,00,000</option><option>₹5,00,000+</option></select></label></div><label className="wc-message-label">A little about your idea<textarea name="message" value={form.message} onChange={change} placeholder="What would you like your website to do? What should it feel like?" rows="5" required maxLength="3000"/></label><div className="wc-form-foot"><span>We’ll only use this to reply about your project.</span><button type="submit" disabled={state==="loading"}>{state==="loading"?<LoaderCircle size={17} className="spin"/>:<Send size={16}/>} Send project request</button></div></form>}</section></div></main>;
}
